language: go

go:
  - tip

go_import_path: gopkg.in/dedis/kyber.v1

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls


script:
  - make test

notifications:
      email: false
